# Generated by Django 6.0.2 on 2026-03-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_result_score_result_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
