# Generated by Django 6.0.3 on 2026-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_profile_profile_pic_alter_profile_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authority_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
