# Generated by Django 6.0.3 on 2026-04-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_result_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
